# NumPy 4 – Aggregation und Broadcasting

**Szenario:** Die Geschäftsführung der *Kiez Kaffee GmbH* möchte einen **Report**:
Welche Filiale ist am stärksten? Wie viel Prozent trägt jede Filiale bei? Wie entwickelt sich der Umsatz? Und was tun mit fehlenden Daten?

**Heute:** Prozentrechnung mit Arrays · Summen und Durchschnitte (auch pro Zeile/Spalte) · laufende Summen und Wachstum · fehlende Werte (NaN) · Broadcasting

In [3]:
import numpy as np

filialen = np.array(["Kreuzberg", "Neukölln", "Friedrichshain", "Wedding"])
tage = np.array(["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"])

# Umsätze einer Woche in €: Zeilen = Filialen, Spalten = Tage
woche = np.array([
    [820, 950, 780, 1100, 1340, 1500, 1200],
    [610, 700, 690,  720,  980, 1150,  900],
    [900, 870, 910,  950, 1210, 1380, 1250],
    [540, 600, 580,  610,  800,  950,  700],
])
print(np.shape(woche))

(4, 7)


# A – Brücke zur Mathe: Prozent, Dreisatz, Wachstum

## 1 – Prozentrechnung mit Arrays

Die drei Grundformeln von heute Morgen gelten unverändert, nur rechnet NumPy sie für **alle Werte gleichzeitig**:

| Gesucht | Formel | NumPy |
|---|---|---|
| Prozentwert W | W = G · p / 100 | `G * p / 100` |
| Prozentsatz p | p = W / G · 100 | `W / G * 100` |
| Grundwert G | G = W · 100 / p | `W * 100 / p` |

In [6]:
# Wochenziel je Filiale (Grundwert) und erreichter Umsatz am Montag (Prozentwert)
wochenziel = np.array([7000, 5500, 7000, 4500])
montag = woche[:, 0]

print(woche)
print("Montag in % vom Wochenziel:", np.round(montag / wochenziel * 100, 1))
print("20 % Rabatt auf die Montagsumsätze:", montag * 0.20)             # * 0,20

[[ 820  950  780 1100 1340 1500 1200]
 [ 610  700  690  720  980 1150  900]
 [ 900  870  910  950 1210 1380 1250]
 [ 540  600  580  610  800  950  700]]
Montag in % vom Wochenziel: [11.7 11.1 12.9 12. ]
20 % Rabatt auf die Montagsumsätze: [164. 122. 180. 108.]


## 2 – Veränderung in Prozent und Wachstumsfaktor

- **Veränderung in %** = (neu − alt) / alt · 100
- **Wachstumsfaktor** q = 1 + p / 100 (bei +5 % ist q = 1,05, bei −5 % ist q = 0,95)
- **Wachstum über n Perioden:** Kₙ = K₀ · qⁿ

Mit einem Array von Exponenten bekommen wir die komplette Entwicklung in einer Zeile:

In [9]:
montag_vorwoche = np.array([780, 640, 950, 500]) # "Kreuzberg", "Neukölln", "Friedrichshain", "Wedding"
print(montag)
print("Veränderung in %:", np.round((montag - montag_vorwoche) / montag_vorwoche * 100, 1))

# 5 % Wachstum pro Jahr, Startumsatz 250 000 €, Jahre 0 bis 5
jahre = np.arange(0, 6)
print("Umsatz:", np.round(250_000 * 1.05 ** jahre))
variable =  np.round(250_000 * 1.05 ** jahre)
print(np.array(variable * 1.05 ** jahre))

[820 610 900 540]
Veränderung in %: [ 5.1 -4.7 -5.3  8. ]
Umsatz: [250000. 262500. 275625. 289406. 303877. 319070.]
[250000.         275625.         303876.5625     335023.62075
 369364.39273125 407223.15814688]


## 3 – Dreisatz

Der Dreisatz ist **Umrechnen über die Einheit**: Aus 250 g Bohnen macht man 12 Tassen, also aus 1 g 12/250 Tassen.
Mit einem Array kann man beliebig viele Mengen auf einmal umrechnen:

In [10]:
gramm = np.array([250, 500, 1000, 75])
tassen = gramm * 12 / 250
print(tassen)

[12.  24.  48.   3.6]


### Übung 1 – Preise und Ziele

👥 **Gemeinsame Übung**

1. Die Preise `np.array([4.20, 3.10, 5.40])` steigen um **8 %**. Berechne die neuen Preise (2 Stellen).
2. Am Samstag lag der Umsatz aller Filialen bei `woche[:, 5]`. Wie viel **Prozent vom Wochenziel** ist das?
3. Eine Filiale wächst jedes Jahr um **3 %**. Wie hoch ist der Umsatz in den Jahren 0 bis 10, wenn er heute 180 000 € beträgt?
4. **Dreisatz:** 3 Baristas schaffen 90 Tassen pro Stunde. Wie viele Tassen schaffen 1, 2, 4 und 5 Baristas?

In [ ]:
# Dein Code hier
# 1
preise = np.array([4.20, 3.10, 5.40])
neue_preise = preise * 1.08
print(np.round(neue_preise, 2))
print(np.round(np.array([4.20, 3.10, 5.40]) * 1.08, 2))
print()
# 2
print(woche[:, 5])  # Sa. alle Filialen
print(wochenziel)
# Prozentsatz suche: p = W Prozentwert/ G Grundwert * 100
print(np.round(woche[:, 5]/ wochenziel * 100, 1))
print()
# 3
jahre = np.arange(0, 11)
print("Umsatz:", np.round(180_000 * 1.03 ** jahre))
print()
zinsen_zins =  np.round(180_000 * 1.03 ** jahre)
print(np.round(np.array(zinsen_zins * 1.03 ** jahre), 2))
print()
# 4
baristas = np.array([1, 2, 4, 5, 100])
print(baristas * 90 / 3)


[4.54 3.35 5.83]
[4.54 3.35 5.83]

[1500 1150 1380  950]
[7000 5500 7000 4500]
[21.4 20.9 19.7 21.1]

Umsatz: [180000. 185400. 190962. 196691. 202592. 208669. 214929. 221377. 228019.
 234859. 241905.]

[180000.   190962.   202591.59 214929.57 228019.08 241904.56 256636.47
 272265.79 288847.65 306437.73 325100.09]

[  30.   60.  120.  150. 3000.]


# B – Aggregationen: Daten zusammenfassen

## 4 – Ein ganzes Array zu einer Zahl machen

**Aggregieren** heißt: Viele Werte werden zu **einem** Wert zusammengefasst.

| Methode | Ergebnis |
|---|---|
| `arr.sum()` | Summe |
| `arr.mean()` | Mittelwert (Durchschnitt) |
| `arr.min()` / `arr.max()` | kleinster / größter Wert |
| `arr.argmin()` / `arr.argmax()` | **Position** des kleinsten / größten Werts |

Statt `arr.sum()` kann man auch `np.sum(arr)` schreiben, das Ergebnis ist gleich.

In [41]:
kb = woche[0, :]  
print(kb.dtype)
# print(woche)    # Kreuzberg, ganze Woche
print(kb)
print(tage)


print("Summe       :", kb.sum())
print("Durchschnitt:", kb.mean())
print("Minimum     :", kb.min(), "am", tage[kb.argmin()])
print("Maximum     :", kb.max(), "am", tage[kb.argmax()])

int64
[ 820  950  780 1100 1340 1500 1200]
['Mo' 'Di' 'Mi' 'Do' 'Fr' 'Sa' 'So']
Summe       : 7690
Durchschnitt: 1098.5714285714287
Minimum     : 780 am Mi
Maximum     : 1500 am Sa


`argmax` ist besonders nützlich: Mit der Position kann man im **passenden Namens-Array** nachschlagen, *wer* oder *wann* das Maximum hatte.

> 💡 **Kurz erwähnt:** Es gibt auch `arr.std()` (Standardabweichung) und `arr.var()` (Varianz). Was die bedeuten, lernst du in der Statistik-Woche.

## 5 – Der Parameter `axis`: pro Zeile oder pro Spalte?

Bei einer Tabelle will man meist **nicht** alles zu einer Zahl zusammenfassen, sondern **pro Filiale** oder **pro Tag**.
Dafür gibt es den Parameter `axis`:

```
                 Mo    Di    Mi    Do    Fr    Sa    So      axis=1  →  eine Summe pro ZEILE
Kreuzberg       820   950   780  1100  1340  1500  1200   →  7690
Neukölln        610   700   690   720   980  1150   900   →  5750
Friedrichshain  900   870   910   950  1210  1380  1250   →  7470
Wedding         540   600   580   610   800   950   700   →  4780
                 ↓     ↓     ↓     ↓     ↓     ↓     ↓
axis=0  →      2870  3120  2960  3380  4330  4980  4050      eine Summe pro SPALTE
```

**Merkhilfe:** `axis` gibt die Richtung an, in der zusammengefasst wird, und diese Achse **verschwindet**.

- `axis=0`: nach **unten** zusammenfassen → ein Wert **pro Spalte** (hier: pro Tag)
- `axis=1`: nach **rechts** zusammenfassen → ein Wert **pro Zeile** (hier: pro Filiale)

In [44]:
print("Summe pro Filiale (axis=1):", woche.sum(axis=1))
print("Summe pro Tag     (axis=0):", woche.sum(axis=0))
print("Ø pro Tag             :", np.round(woche.mean(axis=0), 1))
print("stärkster Tag je Filiale  :", tage[woche.argmax(axis=1)])

Summe pro Filiale (axis=1): [7690 5750 7470 4780]
Summe pro Tag     (axis=0): [2870 3120 2960 3380 4330 4980 4050]
Ø pro Tag             : [ 717.5  780.   740.   845.  1082.5 1245.  1012.5]
stärkster Tag je Filiale  : ['Sa' 'Sa' 'Sa' 'Sa']


## 6 – Masken zählen und Anteile berechnen

Aus Notebook 3 weißt du: `True` zählt als 1, `False` als 0. Damit wird es praktisch:

- `(bedingung).sum()` → **wie viele** Werte erfüllen die Bedingung?
- `(bedingung).mean()` → **welcher Anteil** erfüllt sie? (mal 100 = Prozent)

In [51]:
ueber_1000 = woche > 1000
print(woche)

print("Anzahl Tage > 1000 € gesamt :", ueber_1000.sum())
print("Anzahl je Filiale           :", ueber_1000.sum(axis=1))
print(ueber_1000.mean())
print("Anteil in % gesamt          :", round(ueber_1000.mean() * 100, 1))

[[ 820  950  780 1100 1340 1500 1200]
 [ 610  700  690  720  980 1150  900]
 [ 900  870  910  950 1210 1380 1250]
 [ 540  600  580  610  800  950  700]]
Anzahl Tage > 1000 € gesamt : 8
Anzahl je Filiale           : [4 1 3 0]
0.2857142857142857
Anteil in % gesamt          : 28.6


### Übung 2 – Wochenreport

👥 **Gemeinsame Übung**

Arbeite mit `woche`.

1. Wie hoch war der **Gesamtumsatz** aller Filialen in dieser Woche?
2. Welche Filiale hatte den **höchsten Wochenumsatz**? (Namen ausgeben!)
3. Wie hoch war der **durchschnittliche Tagesumsatz** jeder Filiale?
4. An welchem Tag war der Umsatz **über alle Filialen** am niedrigsten?
5. Wie viel Prozent aller Tagesumsätze lagen **unter 700 €**?

In [63]:
# Dein Code hier
print(woche)
print(filialen)
print()
# 1
print(woche.sum())
print()
# 2
print(filialen[woche.sum(axis=1).argmax()])
print()
# 3
print(woche.mean(axis=0))
print()
# 4
print(tage[woche.sum(axis=0).argmin()])
print()
# 5
print((woche < 700).mean() * 100)

[[ 820  950  780 1100 1340 1500 1200]
 [ 610  700  690  720  980 1150  900]
 [ 900  870  910  950 1210 1380 1250]
 [ 540  600  580  610  800  950  700]]
['Kreuzberg' 'Neukölln' 'Friedrichshain' 'Wedding']

25690

Kreuzberg

[ 717.5  780.   740.   845.  1082.5 1245.  1012.5]

Mo

21.428571428571427


# C – Laufende Summen, Veränderungen, Wachstum

## 7 – `cumsum`: die laufende Summe

`np.cumsum` (*kumulierte Summe*) addiert Schritt für Schritt auf: Jede Stelle enthält die Summe **bis einschließlich** dieses Werts.

```
Umsatz :  820   950   780  1100 ...
cumsum :  820  1770  2550  3650 ...
```

Typische Frage: **Ab wann** ist ein Ziel erreicht?

In [64]:
laufend = np.cumsum(kb)
print(kb)
print(laufend)

ziel = 5000
print("Ziel erreicht ab:", tage[laufend >= ziel][0])   # [0] = erster Treffer

[ 820  950  780 1100 1340 1500 1200]
[ 820 1770 2550 3650 4990 6490 7690]
Ziel erreicht ab: Sa


## 8 – `np.diff`: Veränderung zum Vorwert

`np.diff(arr)` berechnet die Differenz zwischen **benachbarten** Werten. Das Ergebnis ist **ein Element kürzer**.
Die Veränderung in Prozent ist dann: Differenz / alter Wert · 100.

In [ ]:
print("Umsatz      :", kb)
print("Differenz   :", np.diff(kb))
print("Veränd. in %:", np.round(np.diff(kb) / * 100, 1))   # kb[:-1] = alle außer dem letzten

Umsatz      : [ 820  950  780 1100 1340 1500 1200]
Differenz   : [ 130 -170  320  240  160 -300]
Veränd. in %: [ 15.9 -17.9  41.   21.8  11.9 -20. ]


## 9 – `cumprod`: Wachstum mit wechselnden Raten

Wächst etwas jedes Jahr um einen **anderen** Prozentsatz, multipliziert man die Wachstumsfaktoren nacheinander:
K₃ = K₀ · q₁ · q₂ · q₃

Genau das macht `np.cumprod` (*kumuliertes Produkt*):

In [72]:
raten = np.array([4, -2, 6, 3])        # Wachstum in % für 4 Jahre
faktoren = 1 + raten / 100
print("Faktoren  :", faktoren)
print("kumuliert :", np.round(np.cumprod(faktoren), 5))

start = 250_000
print("Umsatz    :", np.round(start * np.cumprod(faktoren)))

Faktoren  : [1.04 0.98 1.06 1.03]
kumuliert : [1.04    1.0192  1.08035 1.11276]
Umsatz    : [260000. 254800. 270088. 278191.]


### Übung 3 – Monatsziel

👥 **Gemeinsame Übung**

Kreuzberg hatte im Oktober diese Umsätze pro Woche (in €): `np.array([7690, 8120, 7350, 8900])`.

1. Berechne den **laufenden** Monatsumsatz.
2. In welcher Woche (1–4) wurden **25 000 €** überschritten? (Tipp: `np.arange(1, 5)` als Wochennummern)
3. Berechne die Veränderung **in %** von Woche zu Woche.
4. Die Filiale plant für die nächsten 3 Monate Wachstum von **+2 %, +5 %, −1 %**. Wie hoch ist der Monatsumsatz danach jeweils, wenn Oktober der Ausgangswert ist?

In [81]:
# Dein Code hier
okt = np.array([7690, 8120, 7350, 8900])
# 1
laufend = np.cumsum(okt)
print(laufend)
print()
# 2
print(woche)
wochen = np.arange(1, 5)
print(wochen[laufend > 25_000][0])
print()
# 3
print(np.round(np.diff(okt) / okt[:-1] * 100, 1))
print()
# 4
faktoren = 1 + np.array([2, 5, -1]) / 100
print(okt.sum() * np.cumprod(faktoren))

[ 7690 15810 23160 32060]

[[ 820  950  780 1100 1340 1500 1200]
 [ 610  700  690  720  980 1150  900]
 [ 900  870  910  950 1210 1380 1250]
 [ 540  600  580  610  800  950  700]]
4

[ 5.6 -9.5 21.1]

[32701.2    34336.26   33992.8974]


# D – Fehlende Werte und Ausreißer

## 10 – `np.nan`: ein Platzhalter für „fehlt"

Erinnerst du dich an Notebook 1? Dort haben wir Buchungsfehler auf **0** gesetzt. Aber 0 € Umsatz ist etwas anderes als „keine Daten"!
Für fehlende Werte gibt es `np.nan` (*Not a Number*).

Drei Dinge musst du wissen:

1. `np.nan` ist eine **Kommazahl**. Ein Integer-Array kann kein NaN enthalten, man braucht `float`.
2. NaN ist **ansteckend**: Jede Rechnung mit NaN ergibt NaN.
3. NaN ist **nicht einmal gleich sich selbst**: `np.nan == np.nan` ist `False`. Zum Prüfen gibt es `np.isnan()`.

In [83]:
kasse = np.array([820, np.nan, 780, 1100, np.nan, 1500, 1200])
print(kasse, kasse.dtype)

print("Summe          :", kasse.sum())         # NaN steckt an
print("nan == nan     :", np.nan == np.nan)
print("isnan          :", np.isnan(kasse))
print("Anzahl fehlend :", np.isnan(kasse).sum())
print(len(kasse))

[ 820.   nan  780. 1100.   nan 1500. 1200.] float64
Summe          : nan
nan == nan     : False
isnan          : [False  True False False  True False False]
Anzahl fehlend : 2
7


## 11 – Mit NaN rechnen

| Ziel | Lösung |
|---|---|
| NaN beim Rechnen ignorieren | `np.nansum`, `np.nanmean`, `np.nanmin`, `np.nanmax` … |
| NaN herausfiltern | `arr[~np.isnan(arr)]` |
| NaN durch einen Wert ersetzen | `np.where(np.isnan(arr), ersatz, arr)` |

In [ ]:
kasse = np.array([820, np.nan, 780, 1100, np.nan, 1500, 1200])
print("nansum   :", np.nansum(kasse))
print("nanmean  :", round(np.nanmean(kasse), 1))
print("gefiltert:", kasse[~np.isnan(kasse)])

ersetzt = np.where(np.isnan(kasse), np.nanmean(kasse), kasse)
print("ersetzt  :", np.round(ersetzt))

nansum   : 5400.0
gefiltert: [ 820.  780. 1100. 1500. 1200.]
ersetzt  : [ 820. 1080.  780. 1100. 1080. 1500. 1200.]


**Achtung:** Ob man NaN ignoriert, herausfiltert oder ersetzt, ist eine **fachliche** Entscheidung, keine technische.
Wer fehlende Tage mit dem Durchschnitt füllt, tut so, als hätte es diese Umsätze gegeben.

## 12 – `np.clip`: Werte auf einen Bereich begrenzen

Der Röstofen misst die Temperatur. Manchmal liefert der Sensor unsinnige Werte (z. B. 0 °C oder 999 °C).
Bekannt ist: Realistisch sind nur Werte **zwischen 180 und 240 °C**.

`np.clip(arr, untergrenze, obergrenze)`:
- alles **unter** der Untergrenze wird zur Untergrenze
- alles **über** der Obergrenze wird zur Obergrenze
- alles dazwischen bleibt unverändert

In [88]:
temperatur = np.array([205, 212, 0, 219, 226, 999, 231, 228, 175])

print("roh    :", temperatur)
print("clip   :", np.clip(temperatur, 180, 240))

roh    : [205 212   0 219 226 999 231 228 175]
clip   : [205 212 180 219 226 240 231 228 180]


`np.clip` macht dasselbe wie zwei verschachtelte `np.where`, ist aber kürzer und lesbarer:

In [89]:
per_where = np.where(temperatur < 180, 180, np.where(temperatur > 240, 240, temperatur))
print(per_where)

[205 212 180 219 226 240 231 228 180]


> 💡 **Kurz erwähnt:** Ob man Ausreißer **begrenzt** (clip) oder **als fehlend markiert** (NaN), hängt wieder von der Fachfrage ab.
> Ein Sensor, der 999 °C meldet, hat eigentlich *gar nichts* gemessen. Dann wäre NaN ehrlicher.

Tagesumsätze der Filiale Wedding (2 Wochen):

In [ ]:
wedding = np.array([540, 600, np.nan, 610, 800, 950, 700,
                    560, np.nan, 590, 6400, 820, 990, np.nan])

### Übung 4 – Kassendaten bereinigen

👥 **Gemeinsame Übung**

Die Filiale Wedding hat ihre Tagesumsätze der letzten zwei Wochen geliefert (`wedding`, Zelle oben).
An manchen Tagen fehlt die Meldung (NaN), an einem Tag wurde ein Tippfehler gebucht.

1. An wie vielen Tagen fehlen Werte?
2. Wie hoch ist der **Durchschnitt** der vorhandenen Werte?
3. Realistisch sind nur Umsätze **zwischen 300 und 2000 €**. Begrenze die Werte mit `np.clip` und berechne den Durchschnitt erneut. Was fällt dir auf?
4. Ersetze die fehlenden Werte durch **0** und vergleiche die Summe mit `np.nansum` der Originaldaten.

In [97]:
# Dein Code hier
wedding = np.array([540, 600, np.nan, 610, 800, 950, 700,
                    560, np.nan, 590, 6400, 820, 990, np.nan])
# 1
print(np.isnan(wedding).sum())
# 2
print(np.nanmean(wedding))
# 3
begrenzt = np.clip(wedding, 300, 2000)
print(begrenzt)
print(np.nanmean(begrenzt))
# 4
null = np.where(np.isnan(wedding), 0, wedding)
print(null)
print(null.sum(), np.nansum(wedding))


3
1232.7272727272727
[ 540.  600.   nan  610.  800.  950.  700.  560.   nan  590. 2000.  820.
  990.   nan]
832.7272727272727
[ 540.  600.    0.  610.  800.  950.  700.  560.    0.  590. 6400.  820.
  990.    0.]
13560.0 13560.0


# E – Broadcasting: Arrays unterschiedlicher Form verrechnen

## 13 – Warum funktioniert `arr + 4`?

Eigentlich rechnet NumPy nur Arrays **gleicher Form** Element für Element.
Trotzdem funktioniert `np.array([1, 2, 3, 4]) + 4`. Der Grund: NumPy **streckt** die 4 gedanklich auf die passende Form:

```
[1, 2, 3, 4]        [1, 2, 3, 4]
     +         →         +
     4              [4, 4, 4, 4]
```

Dieses automatische Strecken heißt **Broadcasting**. Es funktioniert nicht nur mit einzelnen Zahlen, sondern auch mit ganzen Zeilen und Spalten.

## 14 – Eine Zeile auf eine Tabelle anwenden

`woche` hat die Form `(4, 7)`. Ein Array mit **7** Werten (eines pro Tag) wird auf **jede Zeile** angewendet:

```
woche (4, 7)                     zuschlag (7,)
[ 820  950 ... 1200]      +      [0 0 0 0 0 50 50]    ← wird für jede Zeile wiederholt
[ 610  700 ...  900]      +      [0 0 0 0 0 50 50]
[ 900  870 ... 1250]      +      [0 0 0 0 0 50 50]
[ 540  600 ...  700]      +      [0 0 0 0 0 50 50]
```

In [100]:
zuschlag = np.array([0, 0, 0, 0, 0, 50, 50])   # Wochenend-Aktion: +50 € pro Filiale
print(woche + zuschlag)
print()

# Abweichung jeder Filiale vom Tagesdurchschnitt aller Filialen
tages_schnitt = woche.mean(axis=0)            # Form (7,)
print(tages_schnitt)
print()
print(np.round(woche - tages_schnitt))

[[ 820  950  780 1100 1340 1550 1250]
 [ 610  700  690  720  980 1200  950]
 [ 900  870  910  950 1210 1430 1300]
 [ 540  600  580  610  800 1000  750]]

[ 717.5  780.   740.   845.  1082.5 1245.  1012.5]

[[ 102.  170.   40.  255.  258.  255.  188.]
 [-108.  -80.  -50. -125. -102.  -95. -112.]
 [ 182.   90.  170.  105.  128.  135.  238.]
 [-178. -180. -160. -235. -282. -295. -312.]]


## 15 – Eine Spalte auf eine Tabelle anwenden

Jetzt wollen wir **pro Filiale** rechnen, z. B. den Anteil jedes Tages am **Wochenumsatz der Filiale**.
Die Wochensumme hat 4 Werte, einen pro Zeile. Aber:

In [103]:
summe_filiale = woche.sum(axis=1)
print(summe_filiale.shape)

try:
    woche / summe_filiale
except ValueError as e:
    print("Fehler:", e)

(4,)
Fehler: operands could not be broadcast together with shapes (4,7) (4,) 


NumPy vergleicht die Formen **von rechts**: `(4, 7)` und `(4,)` → 7 und 4 passen nicht.
Wir müssen aus den 4 Werten eine **Spalte** machen, also die Form `(4, 1)`. Dafür gibt es zwei Wege:

- `keepdims=True` beim Aggregieren: die zusammengefasste Achse bleibt mit Länge 1 erhalten
- `[:, np.newaxis]`: fügt nachträglich eine Achse der Länge 1 hinzu

```
woche (4, 7)                         summe (4, 1)
[ 820  950 ... 1200]       /         [7690]    ← wird nach rechts wiederholt
[ 610  700 ...  900]       /         [5750]
[ 900  870 ... 1250]       /         [7470]
[ 540  600 ...  700]       /         [4780]
```

In [105]:
summe_spalte = woche.sum(axis=1, keepdims=True)
print(summe_spalte.shape)

anteil = woche / summe_spalte * 100
print(np.round(anteil, 1))
print("Kontrolle, jede Zeile = 100 %:", np.round(anteil.sum(axis=1)))

# gleiches Ergebnis mit np.newaxis
print(summe_filiale)
print(summe_filiale[:, np.newaxis].shape)

(4, 1)
[[10.7 12.4 10.1 14.3 17.4 19.5 15.6]
 [10.6 12.2 12.  12.5 17.  20.  15.7]
 [12.  11.6 12.2 12.7 16.2 18.5 16.7]
 [11.3 12.6 12.1 12.8 16.7 19.9 14.6]]
Kontrolle, jede Zeile = 100 %: [100. 100. 100. 100.]
[7690 5750 7470 4780]
(4, 1)


**Kurzregel für Broadcasting:** Vergleiche die Formen **von rechts nach links**. Zwei Längen passen, wenn sie **gleich** sind oder eine davon **1** ist.

| Form A | Form B | passt? |
|---|---|---|
| `(4, 7)` | `(7,)` | 7 = 7 |
| `(4, 7)` | `(4, 1)` | 7 und 1, 4 = 4 |
| `(4, 7)` | `(4,)` | 7 ≠ 4 |

> 💡 **Kurz erwähnt:** Die offiziellen Broadcasting-Regeln in der NumPy-Dokumentation sind etwas formaler (fehlende Achsen werden links mit 1 aufgefüllt usw.). Für unsere Zwecke reicht die Kurzregel.

## 16 – Quiz

Überlege zuerst selbst, dann aufklappen.

**Frage 1:** `x = np.array([1, 2, 3])`. Welche Form hat `x[:, np.newaxis]`?
A) `(3,)`  B) `(1, 3)`  C) `(3, 1)`

<details><summary>Lösung</summary>

**C) `(3, 1)`**: Die neue Achse steht an zweiter Stelle, aus 3 Werten wird eine Spalte.
</details>

**Frage 2:** `x` und `y` haben beide die Form `(3,)`. Was musst du mit `x` machen, damit `x + y` eine **3×3-Matrix** ergibt?
A) `x[np.newaxis, :]`  B) `x[:, np.newaxis]`  C) `np.newaxis + x`

<details><summary>Lösung</summary>

**B)**: `(3, 1)` + `(3,)` → Spalte trifft Zeile → `(3, 3)`.
</details>

**Frage 3:** Was ergibt `np.array([[1], [2]]) + np.array([10, 20, 30])`?
A) `[[11 21 31] [12 22 32]]`  B) `[11 22 33]`  C) Fehler

<details><summary>Lösung</summary>

**A)**: `(2, 1)` + `(3,)` → `(2, 3)`. Die Spalte wird nach rechts, die Zeile nach unten gestreckt.
</details>

In [106]:
# Zum Nachprüfen
x = np.array([1, 2, 3])
print(x[:, np.newaxis].shape)
print(x[:, np.newaxis] + x)
print(np.array([[1], [2]]) + np.array([10, 20, 30]))

(3, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]]
[[11 21 31]
 [12 22 32]]


### Übung 5 – Anteile im Wochenreport

👥 **Gemeinsame Übung**

Arbeite mit `woche`.

1. Welchen **Anteil in %** hat jede Filiale an der **Tagessumme** aller Filialen? (Jede **Spalte** soll 100 % ergeben.)
2. Welchen **Anteil in %** hat jeder Tag am **Wochenumsatz der jeweiligen Filiale**? (Jede **Zeile** soll 100 % ergeben.)
3. Um wie viel Prozent weicht jeder Tagesumsatz vom **Durchschnitt der eigenen Filiale** ab?

Prüfe bei 1 und 2 mit `.sum(axis=...)`, ob wirklich 100 % herauskommen.

In [124]:
# Dein Code hier
print(woche)
# 1
anteil_tag = woche / woche.sum(axis=0) * 100

print()
print(np.round(anteil_tag, 1))
print()
print(anteil_tag.sum(axis=0))
# 2
anteil_filiale = woche / woche.sum(axis=1, keepdims=True) * 100
print()
print(np.round(anteil_filiale, 1))
print()
print(np.round(anteil_filiale.sum(axis=1), 1))
# 3 Durchschnitt pro Filiale als Spalte
durchschitt = woche.mean(axis=1, keepdims=True)
print()
print(np.round((woche - durchschitt) / durchschitt * 100, 1))

[[ 820  950  780 1100 1340 1500 1200]
 [ 610  700  690  720  980 1150  900]
 [ 900  870  910  950 1210 1380 1250]
 [ 540  600  580  610  800  950  700]]

[[28.6 30.4 26.4 32.5 30.9 30.1 29.6]
 [21.3 22.4 23.3 21.3 22.6 23.1 22.2]
 [31.4 27.9 30.7 28.1 27.9 27.7 30.9]
 [18.8 19.2 19.6 18.  18.5 19.1 17.3]]

[100. 100. 100. 100. 100. 100. 100.]

[[10.7 12.4 10.1 14.3 17.4 19.5 15.6]
 [10.6 12.2 12.  12.5 17.  20.  15.7]
 [12.  11.6 12.2 12.7 16.2 18.5 16.7]
 [11.3 12.6 12.1 12.8 16.7 19.9 14.6]]

[100. 100. 100. 100.]

[[-25.4 -13.5 -29.    0.1  22.   36.5   9.2]
 [-25.7 -14.8 -16.  -12.3  19.3  40.    9.6]
 [-15.7 -18.5 -14.7 -11.   13.4  29.3  17.1]
 [-20.9 -12.1 -15.1 -10.7  17.2  39.1   2.5]]


# F – Übungen zum selbstständigen Arbeiten

Hier übst du allein oder zu zweit. Die Übungen sind nach **Themen** sortiert.
Bei jeder Übung steht, zu welchem Block sie gehört. Wenn du bei einer Aufgabe hängst, schau im passenden Block nach.

## 17 – Daten für die Übungen

Führe diese Zelle zuerst aus:

- `monate`: Monatsnamen
- `jahr`: Monatsumsätze (in Tsd. €) der **4 Filialen** (Zeilen) über **12 Monate** (Spalten). Zwei Monatsmeldungen fehlen (NaN).
- `ofen`: Temperaturmessungen des Röstofens in °C, mit Sensorfehlern

In [ ]:
monate = np.array(["Jan", "Feb", "Mär", "Apr", "Mai", "Jun",
                   "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"])

rng = np.random.default_rng(4)
jahr = rng.integers(20, 50, size=(4, 12)).astype(float)
jahr[1, 3] = np.nan      # Neukölln, April fehlt
jahr[3, 8] = np.nan      # Wedding, September fehlt

ofen = np.array([198, 205, 211, 0, 219, 224, 228, 1023, 231, 236, 239, 244, 238, 160])

print(jahr)

## 18 – Thema: Prozent, Dreisatz, Wachstum

### Übung 6 – Preiskalkulation

📌 **Thema:** Prozent, Dreisatz, Wachstum (Block A)

Kiez Kaffee kauft Rohkaffee ein. Einkaufspreise pro kg: `ek = np.array([8.40, 11.20, 6.90, 14.50])`.

1. Die Rösterei schlägt **65 %** auf den Einkaufspreis auf. Berechne die Verkaufspreise pro kg (netto).
2. Beim Rösten verliert Kaffee **18 %** Gewicht. Wie viel kg Röstkaffee entstehen aus 1, 5, 10 und 25 kg Rohkaffee?
3. **Dreisatz:** Aus 1 kg Röstkaffee macht man ca. 110 Tassen. Wie viele Tassen ergeben sich aus den Mengen von Aufgabe 2 (auf ganze Tassen abrunden)?

In [ ]:
# Dein Code hier

## 19 – Thema: Aggregationen

### Übung 7 – Jahresbilanz

📌 **Thema:** Aggregationen (Block B)

Arbeite mit `jahr`. Achtung: Es gibt NaN, benutze die passenden `nan`-Funktionen!

1. Wie hoch ist der **Jahresumsatz** jeder Filiale?
2. Welche Filiale hatte den **höchsten** Jahresumsatz?
3. In welchem **Monat** war der Umsatz über alle Filialen am höchsten? (Tipp: `np.nanargmax`)
4. In wie vielen Monaten lag Kreuzberg **über 40 Tsd. €**?

In [ ]:
# Dein Code hier

### Übung 8 – Quartale

📌 **Thema:** Aggregationen (Block B)

1. Schneide mit Slicing das **1. Quartal** (Jan–Mär) aus `jahr` aus und berechne die Quartalssumme **pro Filiale**.
2. Berechne den **Durchschnitt pro Monat** über alle Filialen (ein Wert pro Monat, NaN ignorieren).
3. Wie viel **Prozent** der Monatswerte (ohne NaN) liegen **unter 25 Tsd. €**?

In [ ]:
# Dein Code hier

## 20 – Thema: Laufende Summen und Wachstum

### Übung 9 – Friedrichshain im Jahresverlauf

📌 **Thema:** Laufende Summen und Wachstum (Block C)

Arbeite mit der Zeile von Friedrichshain (`jahr[2]`, keine NaN).

1. Berechne den **laufenden** Jahresumsatz.
2. In welchem Monat wurden **200 Tsd. €** überschritten?
3. Berechne die Veränderung **in %** von Monat zu Monat.
4. In welchem Monat gab es den **stärksten Anstieg** gegenüber dem Vormonat? (Achtung: `np.diff` ist um 1 kürzer!)

In [ ]:
# Dein Code hier

### Übung 10 – Fünfjahresplan

📌 **Thema:** Laufende Summen und Wachstum (Block C)

Der Jahresumsatz aller Filialen zusammen liegt bei `np.nansum(jahr)` Tsd. €.
Für die nächsten 5 Jahre plant die Geschäftsführung diese Wachstumsraten: **+6 %, +4 %, +4 %, −2 %, +5 %**.

1. Berechne den geplanten Umsatz für jedes der 5 Jahre.
2. Um wie viel Prozent liegt der Umsatz im 5. Jahr **insgesamt** über dem heutigen?
3. Welches **konstante** jährliche Wachstum hätte zum gleichen Endwert geführt? (Tipp: 5. Wurzel aus dem Gesamtfaktor)

In [ ]:
# Dein Code hier

## 21 – Thema: NaN und `np.clip`

### Übung 11 – Lücken im Jahresbericht

📌 **Thema:** NaN und `np.clip` (Block D)

1. Wie viele Werte fehlen in `jahr` **insgesamt** und **pro Filiale**?
2. Ersetze jeden fehlenden Wert durch den **Durchschnitt der eigenen Filiale**.
   (Tipp: `np.nanmean(jahr, axis=1, keepdims=True)` und `np.where`, hier hilft Broadcasting!)
3. Vergleiche den Jahresumsatz von Neukölln **mit** und **ohne** Auffüllen. Welche Zahl würdest du der Geschäftsführung melden?

In [ ]:
# Dein Code hier

### Übung 12 – Röstofen

📌 **Thema:** NaN und `np.clip` (Block D)

Arbeite mit `ofen`. Der Ofen arbeitet realistisch zwischen **180 und 250 °C**.

1. Wie viele Messwerte liegen **außerhalb** dieses Bereichs?
2. Begrenze die Werte mit `np.clip` und berechne den Durchschnitt. Vergleiche mit dem Durchschnitt der Rohdaten.
3. Alternative: Setze Werte außerhalb des Bereichs auf **NaN** (Tipp: erst `astype(float)`) und berechne den Durchschnitt mit `np.nanmean`.
   Welche Methode ist hier ehrlicher?

In [ ]:
# Dein Code hier

## 22 – Thema: Broadcasting

Für diesen Abschnitt brauchst du das Array `gefuellt` aus Übung 11 (fehlende Werte durch den Filialdurchschnitt ersetzt).
Falls du Übung 11 nicht gelöst hast, führe diese Zelle aus:

In [ ]:
gefuellt = np.where(np.isnan(jahr), np.nanmean(jahr, axis=1, keepdims=True), jahr)

### Übung 13 – Marktanteile im Jahr

📌 **Thema:** Broadcasting (Block E)

Arbeite mit `gefuellt` (ohne NaN, Zelle oben).

1. Welchen Anteil in % hat jede Filiale am **Monatsumsatz aller Filialen**? (jede Spalte = 100 %)
2. Welchen Anteil in % hat jeder Monat am **Jahresumsatz der jeweiligen Filiale**? (jede Zeile = 100 %)
3. In welchem Monat hatte **Wedding** seinen höchsten Anteil am Gesamtumsatz aller Filialen?

In [ ]:
# Dein Code hier

### Übung 14 – Budget pro Filiale

📌 **Thema:** Broadcasting (Block E)

Jede Filiale hat ein eigenes Monatsbudget (in Tsd. €): `budget = np.array([38, 30, 36, 26])`.

1. Berechne für jede Filiale und jeden Monat die **Abweichung vom Budget** (`gefuellt` minus Budget).
2. In wie vielen Monaten hat jede Filiale ihr Budget **verfehlt**?
3. Welche Form muss `budget` haben, damit Aufgabe 1 funktioniert? Warum klappt es mit Form `(4,)` nicht?

In [ ]:
# Dein Code hier

---
**Morgen:** Gleichungssysteme und Funktionen: Vektoren und Matrizen, Arrays umformen und kombinieren, lineare Gleichungssysteme mit NumPy lösen und Daten sortieren.