# NumPy 5 – Matrizen und Funktionen

**Szenario:** Zum Abschluss der Woche plant die *Kiez Kaffee GmbH* ihr neues Sortiment.
Dafür müssen Mischungen berechnet, Daten aus mehreren Filialen zusammengeführt, Kosten als Funktion dargestellt und Ranglisten erstellt werden.

**Heute:** Vektoren und Matrizen · Arrays umformen (`reshape`) · Arrays kombinieren und aufteilen · Funktionen als Wertetabelle · lineare Gleichungssysteme lösen · Sortieren

In [1]:
import numpy as np

filialen = np.array(["Kreuzberg", "Neukölln", "Friedrichshain", "Wedding"])

# A – Brücke zur Mathe: Gleichungssysteme und Funktionen

## 1 – Ein Gleichungssystem als Matrix

Heute Morgen hast du lineare Gleichungssysteme gelöst, zum Beispiel:

> Kiez Kaffee verkauft Espresso (x) und Crema (y).
> 2 Espresso und 3 Crema kosten zusammen 17 €.
> 4 Espresso und 1 Crema kosten zusammen 19 €.

```
2x + 3y = 17
4x + 1y = 19
```

Man kann das System in **drei Teile** zerlegen:

```
 Koeffizienten A      Unbekannte x      Ergebnisse b
  ┌       ┐           ┌   ┐             ┌    ┐
  │ 2   3 │     ·     │ x │      =      │ 17 │
  │ 4   1 │           │ y │             │ 19 │
  └       ┘           └   ┘             └    ┘
```

Kurz: **A · x = b**. Die Zahlen vor den Unbekannten bilden eine **Matrix** (eine 2D-Tabelle), die Ergebnisse einen **Vektor** (eine Reihe).
Genau so können wir das System in NumPy aufschreiben:

In [2]:
A = np.array([[2, 3],
              [4, 1]])
b = np.array([17, 19])

print("A:\n", A, "\nShape:", A.shape)
print("b:", b, "\nShape:", b.shape)

A:
 [[2 3]
 [4 1]] 
Shape: (2, 2)
b: [17 19] 
Shape: (2,)


Wie man das System mit NumPy **löst**, siehst du in Block D. Vorher brauchen wir noch ein paar Werkzeuge.

## 2 – Eine Funktion als Wertetabelle

Eine Funktion wie **f(x) = 2x + 3** ordnet jedem x einen y-Wert zu. Auf Papier macht man dafür eine **Wertetabelle**:

| x | 0 | 1 | 2 | 3 | 4 |
|---|---|---|---|---|---|
| f(x) | 3 | 5 | 7 | 9 | 11 |

In NumPy ist das eine Zeile: Wir erzeugen alle x-Werte als Array und rechnen die Formel **vektorisiert** aus.

In [3]:
x = np.arange(0, 5)
y = 2 * x + 3

print("x   :", x)
print("f(x):", y)

x   : [0 1 2 3 4]
f(x): [ 3  5  7  9 11]


### Übung 1 – Gleichungssystem aufschreiben und Werte prüfen

👥 **Gemeinsame Übung**

Gegeben ist das Gleichungssystem:

```
 x + 2y = 8
3x -  y = 3
```

1. Schreibe die Koeffizientenmatrix `A2` und den Ergebnisvektor `b2` als NumPy-Arrays auf. Gib die Shapes aus.
2. Die Lösung ist x = 2, y = 3. Prüfe das, indem du die **linken Seiten** beider Gleichungen mit diesen Werten von Hand ausrechnest (z. B. `A2[0, 0] * 2 + A2[0, 1] * 3`).
3. Erstelle eine Wertetabelle für **g(x) = x² − 4** für x von −3 bis 3.
4. Für welche x aus der Tabelle ist g(x) = 0? (Tipp: Maske)

In [ ]:
# Dein Code hier
# 1
A2 = np.array([[1, 2], 
              [3, -1]])
b2 = np.array([8, 3])
print(A2.shape, b2.shape)
# 2 x = 2, y = 3
print(A2[0, 0] * 2 + A2[0, 1] * 3)
print(A2[1, 0] * 2 + A2[1, 1] * 3)
# 3
x = np.arange(-3, 4)
g = x ** 2 - 4
print(x)
print(g)
# 4 Nulstellen
print(x[g == 0])

(2, 2) (2,)
8
3
[-3 -2 -1  0  1  2  3]
[ 5  0 -3 -4 -3  0  5]
[-2  2]


# B – Vektoren, Matrizen und `reshape`

## 3 – Zeilenvektor, Spaltenvektor, 1D-Array

In der Mathe unterscheidet man **Zeilenvektoren** (liegend) und **Spaltenvektoren** (stehend).
NumPy kennt dazu noch das einfache **1D-Array**, das weder Zeile noch Spalte ist:

| Shape | Bedeutung | Aussehen |
|---|---|---|
| `(3,)` | 1D-Array | `[1 2 3]` |
| `(1, 3)` | Zeilenvektor: 1 Zeile, 3 Spalten | `[[1 2 3]]` |
| `(3, 1)` | Spaltenvektor: 3 Zeilen, 1 Spalte | `[[1] [2] [3]]` |

Die Shapes kennst du aus Notebook 1. In Notebook 4 hast du gesehen, warum der Unterschied wichtig ist: beim **Broadcasting**.

In [5]:
v = np.array([1, 2, 3])

print(v, v.shape)
print(v.reshape(1, 3), v.reshape(1, 3).shape)
print(v.reshape(3, 1), v.reshape(3, 1).shape)

[1 2 3] (3,)
[[1 2 3]] (1, 3)
[[1]
 [2]
 [3]] (3, 1)


## 4 – `reshape`: gleiche Daten, neue Form

`arr.reshape(zeilen, spalten)` ordnet die Elemente **neu an**, ohne sie zu verändern.
Die Werte werden dabei **zeilenweise** eingefüllt: erst die erste Zeile von links nach rechts, dann die zweite usw.

**Wichtig:** Die Anzahl der Elemente muss gleich bleiben. 12 Elemente passen in `(3, 4)`, `(4, 3)`, `(2, 6)` …, aber nicht in `(5, 3)`.

```
[ 1  2  3  4  5  6  7  8  9 10 11 12]      reshape(3, 4)       [[ 1  2  3  4]
                                       ─────────────────►       [ 5  6  7  8]
                                                                [ 9 10 11 12]]
```

In [6]:
monate = np.arange(1, 13)
print(monate)

print(monate.reshape(3, 4))
print(monate.reshape(4, 3))

try:
    monate.reshape(5, 3)
except ValueError as e:
    print("Fehler:", e)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Fehler: cannot reshape array of size 12 into shape (5,3)


## 5 – `-1`: NumPy rechnet die fehlende Zahl aus

Oft kennt man nur **eine** der beiden Längen. Dann schreibt man für die andere `-1`, und NumPy rechnet sie aus:

In [52]:
print(monate.reshape(4, -1))     # 4 Zeilen -> 3 Spalten
print(monate.reshape(-1, 6))     # 6 Spalten -> 2 Zeilen
print(monate.reshape(-1, 1).shape)  # Spaltenvektor, egal wie lang

# Zurück zu 1D:
tabelle = monate.reshape(3, 4)
print(tabelle)
print(tabelle.reshape(-1))
print(tabelle.flatten())

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(12, 1)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


> 💡 **Kurz erwähnt – Zeilenweise oder spaltenweise?**
> Im Speicher liegt ein 2D-Array als **eine lange Reihe**. NumPy speichert **zeilenweise** (*row-major*, wie in C).
> Andere Sprachen (z. B. Fortran, R, MATLAB) speichern **spaltenweise** (*column-major*). Deshalb füllt `reshape` zeilenweise auf.
> Mit `reshape(..., order="F")` könnte man spaltenweise auffüllen, das brauchen wir aber nicht.

> 💡 **Kurz erwähnt – Transponieren:** `arr.T` vertauscht Zeilen und Spalten. Aus einer `(3, 4)`-Matrix wird eine `(4, 3)`-Matrix.
> Das ist **nicht** dasselbe wie `reshape(4, 3)`!

In [55]:
print(tabelle)
print()
print(tabelle.T)              # Spalten werden zu Zeilen
print()
print(tabelle.reshape(4, 3))  # nur neu aufgefüllt

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


28 Tagesumsätze der Filiale Kreuzberg (4 Wochen, jeweils Mo–So):

In [9]:
rng = np.random.default_rng(5)
kb_28 = rng.integers(600, 1600, size=28)
print(kb_28)

[1270 1405  622 1407 1068 1115 1230  885 1579  653  877  983 1171 1008
  731  645  601  648  748 1599  790 1252 1350  834  882 1034  863 1574]


### Übung 2 – Tagesdaten in Wochen aufteilen

👥 **Gemeinsame Übung**

Kreuzberg hat 28 Tagesumsätze am Stück geliefert (`kb_28`, Zelle oben).

1. Forme die Daten so um, dass jede **Zeile eine Woche** und jede **Spalte ein Wochentag** (Mo–So) ist.
2. Berechne den Umsatz **pro Woche** und den durchschnittlichen Umsatz **pro Wochentag** (Tipp: `axis` aus Notebook 4).
3. Forme die Daten mit `-1` in **14 Zeilen** um. Wie viele Spalten entstehen? Was bedeutet eine Zeile jetzt?

In [59]:
# Dein Code hier
# 1 28 Tage = 4 wochen x 7 Tage
wochen = kb_28.reshape(4, 7)
print(wochen)
# 2
print("pro Woche",                 wochen.sum(axis=1))
print("Durchchnitt pro Wochentag", np.round(wochen.mean(axis=0), 1))
# 3 28/ 14 = 2
print(kb_28.reshape(14, -1).shape)


[[1270 1405  622 1407 1068 1115 1230]
 [ 885 1579  653  877  983 1171 1008]
 [ 731  645  601  648  748 1599  790]
 [1252 1350  834  882 1034  863 1574]]
pro Woche [8117 7156 5762 7789]
Durchchnitt pro Wochentag [1034.5 1244.8  677.5  953.5  958.2 1187.  1150.5]
(14, 2)


# C – Arrays kombinieren und aufteilen

## 6 – `np.concatenate`: aneinanderhängen

`np.concatenate([a, b, ...], axis=...)` hängt Arrays entlang einer **vorhandenen** Achse aneinander.
Die Anzahl der Dimensionen bleibt gleich.

- `axis=0`: **untereinander** (neue Zeilen). Die Anzahl der **Spalten** muss passen.
- `axis=1`: **nebeneinander** (neue Spalten). Die Anzahl der **Zeilen** muss passen.

```
axis=0                          axis=1
[[1 2 3]                        [[1 2 3] + [[7]   →   [[1 2 3 7]
 [4 5 6]]                        [4 5 6]]   [8]]       [4 5 6 8]]
   +
[[7 8 9]]
   ↓
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```

In [11]:
q1 = np.array([[820, 950, 780],     # Kreuzberg Jan–Mär
               [610, 700, 690]])    # Neukölln  Jan–Mär
q2 = np.array([[900, 1010, 980],    # Kreuzberg Apr–Jun
               [640,  720, 760]])   # Neukölln  Apr–Jun

halbjahr = np.concatenate([q1, q2], axis=1)   # nebeneinander: mehr Monate
print(halbjahr, halbjahr.shape)

fh_q1 = np.array([[880, 860, 900]])           # neue Filiale, (1, 3)
drei = np.concatenate([q1, fh_q1], axis=0)    # untereinander: mehr Filialen
print(drei, drei.shape)

[[ 820  950  780  900 1010  980]
 [ 610  700  690  640  720  760]] (2, 6)
[[820 950 780]
 [610 700 690]
 [880 860 900]] (3, 3)


**Typischer Fehler:** Will man eine **einzelne Zeile** untereinander anhängen, muss sie 2D sein (`(1, 3)`), nicht 1D (`(3,)`).
Hier hilft `reshape(1, -1)` aus Block B:

In [12]:
we_q1 = np.array([540, 600, 580])     # 1D, Shape (3,)

try:
    np.concatenate([q1, we_q1], axis=0)
except ValueError as e:
    print("Fehler:", e)

print(np.concatenate([q1, we_q1.reshape(1, -1)], axis=0))

Fehler: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
[[820 950 780]
 [610 700 690]
 [540 600 580]]


## 7 – `np.stack`: stapeln mit neuer Achse

`np.stack` legt gleich große Arrays übereinander und erzeugt dabei eine **neue Dimension**.
Aus mehreren 1D-Arrays wird so ein 2D-Array, also eine Tabelle:

In [13]:
kreuzberg = np.array([820, 950, 780])
neukoelln = np.array([610, 700, 690])
wedding   = np.array([540, 600, 580])

print(np.stack([kreuzberg, neukoelln, wedding]))           # axis=0: jedes Array wird eine ZEILE
print(np.stack([kreuzberg, neukoelln, wedding], axis=1))   # axis=1: jedes Array wird eine SPALTE

[[820 950 780]
 [610 700 690]
 [540 600 580]]
[[820 610 540]
 [950 700 600]
 [780 690 580]]


| Funktion | Dimensionen | Typischer Einsatz |
|---|---|---|
| `concatenate` | bleiben gleich | Tabellen verlängern (mehr Zeilen/Spalten) |
| `stack` | **+1** | einzelne Reihen zu einer Tabelle zusammensetzen |

## 8 – `np.split`: aufteilen

`np.split(arr, n, axis=...)` teilt ein Array in **n gleich große** Teile. Das Ergebnis ist eine **Liste** von Arrays.

In [14]:
jahr = np.arange(1, 13) * 100      # 12 Monatswerte
quartale = np.split(jahr, 4)
print(quartale)

q1, q2, q3, q4 = np.split(jahr, 4)  # direkt auf Variablen verteilen
print("Q3:", q3)

[array([100, 200, 300]), array([400, 500, 600]), array([700, 800, 900]), array([1000, 1100, 1200])]
Q3: [700 800 900]


> 💡 **Kurz erwähnt – Trennstellen:** Statt einer Anzahl kann man auch **Positionen** angeben: `np.split(jahr, [3, 8])` schneidet **vor** Index 3 und **vor** Index 8.
> Das ergibt drei ungleich große Teile. Die gleiche Wirkung hat Slicing: `jahr[:3]`, `jahr[3:8]`, `jahr[8:]`.

Wochenumsätze (Mo–So) der Filialen:

In [15]:
kb_w = np.array([820, 950, 780, 1100, 1340, 1500, 1200])
nk_w = np.array([610, 700, 690,  720,  980, 1150,  900])
fh_w = np.array([900, 870, 910,  950, 1210, 1380, 1250])
we_w = np.array([540, 600, 580,  610,  800,  950,  700])

### Übung 3 – Filialdaten zusammenführen

👥 **Gemeinsame Übung**

Die drei Filialen schicken ihre Wochenumsätze (Mo–So) jeweils als einzelnes 1D-Array (`kb_w`, `nk_w`, `fh_w`, Zelle oben).

1. Setze die drei Arrays zu einer Tabelle zusammen: **Zeilen = Filialen**, Spalten = Tage. Shape prüfen!
2. Wedding liefert nachträglich: `we_w`. Hänge die Zeile an die Tabelle an.
3. Teile die fertige Tabelle mit `np.split` in **zwei Hälften** (je 2 Filialen).

In [68]:
# Dein Code hier
# 1
tabelle = np.stack([kb_w, nk_w, fh_w])
print(tabelle, tabelle. shape)
print()
# 2
tabelle = np.concatenate([tabelle, we_w.reshape(1, 7)], axis=0)
print(tabelle, tabelle.shape)
print()
# 3
oben, unten = np.split(tabelle, 2, axis=0)
print(oben)
print(unten)

[[ 820  950  780 1100 1340 1500 1200]
 [ 610  700  690  720  980 1150  900]
 [ 900  870  910  950 1210 1380 1250]] (3, 7)

[[ 820  950  780 1100 1340 1500 1200]
 [ 610  700  690  720  980 1150  900]
 [ 900  870  910  950 1210 1380 1250]
 [ 540  600  580  610  800  950  700]] (4, 7)

[[ 820  950  780 1100 1340 1500 1200]
 [ 610  700  690  720  980 1150  900]]
[[ 900  870  910  950 1210 1380 1250]
 [ 540  600  580  610  800  950  700]]


# D – Funktionen und Gleichungssysteme mit NumPy

## 9 – Funktionen mit `np.linspace`

Für eine Wertetabelle mit **vielen** Punkten (z. B. für ein Diagramm) ist `np.linspace` praktisch: Man gibt Start, Ende und **Anzahl** vor.

Beispiel aus der Praxis: Die **Kostenfunktion** einer Röstung.
- Fixkosten (Miete, Maschine): 400 € pro Tag
- Variable Kosten: 6 € pro kg

**K(x) = 6x + 400**, x = gerösteter Kaffee in kg

In [17]:
x = np.linspace(0, 100, 11)     # 0, 10, 20, ..., 100 kg
kosten = 6 * x + 400

print("kg    :", x)
print("Kosten:", kosten)

kg    : [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
Kosten: [ 400.  460.  520.  580.  640.  700.  760.  820.  880.  940. 1000.]


Mit einer zweiten Funktion, dem **Erlös** E(x) = 14x (Verkaufspreis 14 € pro kg), lässt sich der **Gewinn** berechnen und die **Gewinnschwelle** finden:

In [ ]:
x = np.arange(0, 101)           # in 1-kg-Schritten
kosten = 6 * x + 400
erloes = 14 * x
gewinn = erloes - kosten

print("Gewinn bei 0, 25, 50, 100 kg:", gewinn[[0, 25, 50, 100]])
print("Gewinnschwelle ab:", x[gewinn >= 0][0], "kg")

Gewinn bei 0, 25, 50, 100 kg: [-400 -200    0  400]
Gewinnschwelle ab: 51 kg


> 💡 **Kurz erwähnt:** Mit Matplotlib (kommt später im Kurs) zeichnest du daraus mit `plt.plot(x, kosten)` direkt den Funktionsgraphen.

## 10 – Matrixmultiplikation mit `@`

Vorsicht, zwei verschiedene Arten zu multiplizieren:

| Schreibweise | Bedeutung |
|---|---|
| `A * B` | **elementweise** (wie bisher): jedes Element mit dem an gleicher Stelle |
| `A @ B` | **Matrixmultiplikation** (wie in der Mathe): Zeile mal Spalte, dann aufsummieren |

`A @ x` ist genau die **linke Seite** eines Gleichungssystems: Jede Zeile von A wird mit x multipliziert und aufsummiert.

In [19]:
A = np.array([[2, 3],
              [4, 1]])
x_probe = np.array([4, 3])

print("elementweise:", A * x_probe)    # [[2*4, 3*3], [4*4, 1*3]]
print("A @ x       :", A @ x_probe)    # [2*4 + 3*3, 4*4 + 1*3] = [17, 19]

elementweise: [[ 8  9]
 [16  3]]
A @ x       : [17 19]


`A @ x_probe` ergibt `[17, 19]`, also genau `b`. Damit ist x = 4, y = 3 die Lösung des Systems aus Block A.

Ein typischer Einsatz im Alltag: **Mengen × Preise**:

In [20]:
# Bestellungen: Zeilen = Filialen, Spalten = Produkte (Espresso, Crema, Filter)
bestellung = np.array([[10, 5, 8],
                       [ 4, 9, 2],
                       [ 7, 7, 7]])
preise = np.array([12.0, 10.5, 9.0])    # Preis pro Packung

print("Rechnungsbetrag pro Filiale:", bestellung @ preise)

Rechnungsbetrag pro Filiale: [244.5 160.5 220.5]


## 11 – Gleichungssysteme lösen: `np.linalg.solve`

Statt die Lösung zu raten oder per Hand mit dem Additionsverfahren zu rechnen, löst NumPy das System **A · x = b** direkt:

```python
x = np.linalg.solve(A, b)
```

**Immer mit einer Probe abschließen:** `A @ x` muss wieder `b` ergeben. Wegen der Rundung bei Kommazahlen (Notebook 3) prüft man mit `np.allclose`.

```
2x + 3y = 17
4x + 1y = 19
```

In [72]:
loesung = np.linalg.solve(A, b)
print(A)
print(b)
print("Lösung :", loesung)
print("Probe  :", A @ loesung)
print("stimmt?:", np.allclose(A @ loesung, b))

[[2 3]
 [4 1]]
[17 19]
Lösung : [4. 3.]
Probe  : [17. 19.]
stimmt?: True


Das funktioniert genauso für **3 Gleichungen mit 3 Unbekannten**:

> Kiez Kaffee mischt drei Bohnensorten (Brasilien x, Äthiopien y, Kolumbien z) zu **10 kg** Hausmischung.
> Brasilien kostet 8 €/kg, Äthiopien 14 €/kg, Kolumbien 11 €/kg. Die Mischung soll insgesamt **105 €** kosten.
> Von Brasilien soll **doppelt so viel** wie von Kolumbien enthalten sein.

```
 x +  y +  z = 10       (Gesamtmenge)
8x + 14y + 11z = 105    (Gesamtkosten)
 x       - 2z = 0       (x = 2z  →  x - 2z = 0)
```

In [22]:
A3 = np.array([[1,  1,  1],
               [8, 14, 11],
               [1,  0, -2]])
b3 = np.array([10, 105, 0])

mischung = np.linalg.solve(A3, b3)
print("kg Brasilien, Äthiopien, Kolumbien:", np.round(mischung, 2))
print("Probe:", np.allclose(A3 @ mischung, b3))

kg Brasilien, Äthiopien, Kolumbien: [4.67 3.   2.33]
Probe: True


**Wann gibt es keine eindeutige Lösung?** Wenn sich Gleichungen widersprechen oder eine Gleichung nur ein Vielfaches einer anderen ist
(in der Mathe: Die Geraden sind parallel oder identisch). Dann meldet NumPy einen Fehler:

In [23]:
A_parallel = np.array([[1, 2],
                       [2, 4]])     # 2. Zeile = 2 x 1. Zeile
try:
    np.linalg.solve(A_parallel, np.array([5, 10]))
except np.linalg.LinAlgError as e:
    print("Fehler:", e)

Fehler: Singular matrix


### Übung 4 – Preise ermitteln

👥 **Gemeinsame Übung**

Eine Filiale hat zwei Bestellungen aufgegeben, die Einzelpreise sind aber verloren gegangen:

- 3 Packungen Espresso und 2 Packungen Crema haben **57 €** gekostet.
- 1 Packung Espresso und 4 Packungen Crema haben **49 €** gekostet.

1. Stelle das Gleichungssystem als `A` und `b` auf und löse es mit `np.linalg.solve`.
2. Mache die Probe mit `@` und `np.allclose`.
3. Erstelle mit dem Espressopreis eine Wertetabelle für den Preis von **0 bis 10 Packungen** und berechne zusätzlich den Preis mit **15 % Mengenrabatt ab 5 Packungen** (Tipp: `np.where` aus Notebook 2).

In [ ]:
# Dein Code hier
# 3x + 2y = 57
# 1x + 4y = 49
# 1
A_p = np.array([[3, 2], [1, 4]])
b_p = np.array([57, 49])
print(np.linalg.solve(A_p, b_p))
preise = np.linalg.solve(A_p, b_p) # 2 Elementen
# 2
print(np.allclose(A_p @ preise, b_p))
# 3
packungen = np.arange(0, 11)
preis = preise[0] * packungen
mit_rabatt = np.where(packungen >= 5, preis * 0.85, preis)
print(packungen)
print(preis)
print(np.round(mit_rabatt, 2))

[13.  9.]
True
[ 0  1  2  3  4  5  6  7  8  9 10]
[  0.  13.  26.  39.  52.  65.  78.  91. 104. 117. 130.]
[  0.    13.    26.    39.    52.    55.25  66.3   77.35  88.4   99.45
 110.5 ]


# E – Sortieren und Ranglisten

## 12 – `np.sort` und `.sort()`

| Schreibweise | Wirkung | Original |
|---|---|---|
| `np.sort(arr)` | gibt eine **sortierte Kopie** zurück | bleibt unverändert |
| `arr.sort()` | sortiert **direkt im Array** (*in-place*) und gibt `None` zurück | wird verändert |

Sortiert wird immer **aufsteigend**. Für absteigend dreht man das Ergebnis mit `[_:_:-1]` um.

In [25]:
umsatz = np.array([7690, 5750, 7470, 4780])

print("sortiert   :", np.sort(umsatz))
print("absteigend :", np.sort(umsatz)[::-1])
print("Original   :", umsatz)

ergebnis = umsatz.copy().sort()
print("Rückgabe von .sort():", ergebnis)    # None! Häufiger Fehler

sortiert   : [4780 5750 7470 7690]
absteigend : [7690 7470 5750 4780]
Original   : [7690 5750 7470 4780]
Rückgabe von .sort(): None


## 13 – Sortieren in 2D

Bei Tabellen gibt `axis` an, **in welche Richtung** sortiert wird. Jede Zeile bzw. Spalte wird **unabhängig** sortiert:
- `axis=1` (Standard): innerhalb jeder **Zeile**
- `axis=0`: innerhalb jeder **Spalte**

**Achtung:** Dabei werden die Werte innerhalb der Zeilen/Spalten vertauscht. Die Zuordnung zu den Tagen bzw. Filialen geht verloren!

In [ ]:
tabelle = np.stack([kb_w, nk_w, fh_w, we_w])
print(tabelle)
print()
print(np.sort(tabelle, axis=1))   # jede Filiale: Tage aufsteigend (Tag-Zuordnung weg!)

[[ 820  950  780 1100 1340 1500 1200]
 [ 610  700  690  720  980 1150  900]
 [ 900  870  910  950 1210 1380 1250]
 [ 540  600  580  610  800  950  700]]

[[ 540  600  580  610  800  950  700]
 [ 610  700  690  720  980 1150  900]
 [ 820  870  780  950 1210 1380 1200]
 [ 900  950  910 1100 1340 1500 1250]]


## 14 – `np.argsort`: Positionen statt Werte

Oft will man nicht nur die sortierten **Zahlen**, sondern wissen, **wer** auf welchem Platz steht.
`np.argsort` gibt die **Positionen** zurück, in der Reihenfolge, die das Array sortieren würde:

```
umsatz   :  [7690  5750  7470  4780]
Position :     0     1     2     3

argsort  :  [3 1 2 0]    →  erst Position 3 (4780), dann 1 (5750), dann 2, dann 0
```

Diese Positionen kann man mit **Fancy Indexing** (Notebook 2) auf **andere Arrays** anwenden, z. B. auf die Filialnamen:

In [81]:
print(umsatz)
print()
reihenfolge = np.argsort(umsatz)
print("argsort       :", reihenfolge)
print("aufsteigend   :", filialen[reihenfolge])

ranking = np.argsort(umsatz)[::-1]       # absteigend
print("Rangliste     :", filialen[ranking])
print("mit Umsatz    :", umsatz[ranking])

[7690 5750 7470 4780]

argsort       : [3 1 2 0]
aufsteigend   : ['Wedding' 'Neukölln' 'Friedrichshain' 'Kreuzberg']
Rangliste     : ['Kreuzberg' 'Friedrichshain' 'Neukölln' 'Wedding']
mit Umsatz    : [7690 7470 5750 4780]


Genauso lässt sich eine **ganze Tabelle nach einer Spalte sortieren**, ohne dass die Zeilen auseinanderfallen:

In [85]:
# Filialen nach Samstagsumsatz (Spalte 5) sortieren, ganze Zeilen bleiben zusammen
tabelle = np.stack([kb_w, nk_w, fh_w, we_w])
print(tabelle)
print()
pos = np.argsort(tabelle[:, 5])[::-1]
print(filialen[pos])
print(tabelle[pos])

[[ 820  950  780 1100 1340 1500 1200]
 [ 610  700  690  720  980 1150  900]
 [ 900  870  910  950 1210 1380 1250]
 [ 540  600  580  610  800  950  700]]

['Kreuzberg' 'Friedrichshain' 'Neukölln' 'Wedding']
[[ 820  950  780 1100 1340 1500 1200]
 [ 900  870  910  950 1210 1380 1250]
 [ 610  700  690  720  980 1150  900]
 [ 540  600  580  610  800  950  700]]


Sortiment und Jahresumsätze in €:

In [29]:
produkte = np.array(["Espresso", "Crema", "Filter", "Decaf", "Kakao", "Chai"])
jahresumsatz = np.array([186_400, 142_800, 97_300, 21_900, 34_500, 52_100])

### Übung 5 – Top-Produkte

👥 **Gemeinsame Übung**

Kiez Kaffee hat 6 Produkte und ihre Jahresumsätze (`produkte`, `jahresumsatz`, Zelle oben).

1. Sortiere die **Umsätze** absteigend.
2. Erstelle eine **Rangliste der Produktnamen** (bester Umsatz zuerst).
3. Gib die **Top 3** Produkte mit ihren Umsätzen aus.
4. Welchen **Anteil in %** haben die Top 3 am Gesamtumsatz?

In [91]:
# Dein Code hier
# 1
print(np.sort(jahresumsatz)[::-1])
# 2
rang = np.argsort(jahresumsatz)[::-1]
print(produkte[rang])
# 3
top3 = rang[:3]
print(produkte[top3], jahresumsatz[top3])
# 4
gesamtumsatz = jahresumsatz.sum()
top3_gesamt = jahresumsatz[top3].sum()
anteil = np.round(top3_gesamt / gesamtumsatz * 100, 1)
print(anteil)
print(round(jahresumsatz[top3].sum() / jahresumsatz.sum() * 100, 1))

[186400 142800  97300  52100  34500  21900]
['Espresso' 'Crema' 'Filter' 'Chai' 'Kakao' 'Decaf']
['Espresso' 'Crema' 'Filter'] [186400 142800  97300]
79.7
79.7


# F – Übungen zum selbstständigen Arbeiten

Hier übst du allein oder zu zweit. Die Übungen sind nach **Themen** sortiert.
Bei jeder Übung steht, zu welchem Block sie gehört. Wenn du bei einer Aufgabe hängst, schau im passenden Block nach.

Zum Abschluss der Woche kommen in einigen Übungen auch Werkzeuge aus den **Notebooks 1–4** vor.

## 15 – Daten für die Übungen

Führe diese Zelle zuerst aus:

- `tage_jahr`: 364 Tagesumsätze (in €) der Filiale Friedrichshain, also 52 Wochen à 7 Tage am Stück
- `sorten`, `preis_kg`: Rohkaffeesorten und Einkaufspreis pro kg
- `bestand_kg`: Lagerbestand pro Sorte in kg in den 4 Filialen (Zeilen = Filialen, Spalten = Sorten)

In [31]:
rng = np.random.default_rng(55)
tage_jahr = rng.integers(500, 1700, size=364)

sorten = np.array(["Brasilien", "Äthiopien", "Kolumbien", "Guatemala", "Indien"])
preis_kg = np.array([8.0, 14.0, 11.0, 12.5, 7.5])

bestand_kg = np.array([
    [40, 12, 25, 10, 30],
    [22, 18, 30,  5, 15],
    [35, 25, 20, 15, 10],
    [18,  5, 12, 20, 25],
])

np.set_printoptions(suppress=True)   # Zahlen ohne wissenschaftliche Schreibweise (1e+05) anzeigen

## 16 – Thema: Gleichungssysteme und Funktionen

### Übung 6 – Funktionen vergleichen

📌 **Thema:** Gleichungssysteme und Funktionen (Block A)

Zwei Lieferanten bieten Röstkaffee an:

- **Lieferant A:** 50 € Grundgebühr pro Lieferung + 13 € pro kg → A(x) = 13x + 50
- **Lieferant B:** keine Grundgebühr, 15,50 € pro kg → B(x) = 15.5x

1. Erstelle Wertetabellen für beide Lieferanten für **0 bis 40 kg** in 1-kg-Schritten.
2. Ab welcher Menge ist Lieferant A **günstiger**?
3. Prüfe dein Ergebnis rechnerisch: Setze A(x) = B(x) gleich und löse nach x auf (auf Papier oder mit Python).

In [32]:
# Dein Code hier

## 17 – Thema: `reshape`

### Übung 7 – Ein Jahr Friedrichshain

📌 **Thema:** `reshape` (Block B)

Arbeite mit `tage_jahr` (364 Tage am Stück, beginnend mit einem Montag).

1. Forme die Daten in eine Tabelle **52 Wochen × 7 Tage** um.
2. An welchem **Wochentag** ist der durchschnittliche Umsatz am höchsten? (Tipp: Lege dir ein Array mit den Wochentagsnamen an.)
3. Welche **Kalenderwoche** (1–52) hatte den höchsten Umsatz?
4. Forme die Daten in **13 Blöcke à 4 Wochen** um (13 × 28) und berechne die Summe jedes Blocks.

In [33]:
# Dein Code hier

## 18 – Thema: Kombinieren und Aufteilen

### Übung 8 – Quartalsbericht

📌 **Thema:** Kombinieren und Aufteilen (Block C)

1. Teile `tage_jahr` mit `np.split` in **4 Quartale** (je 91 Tage) und berechne den Umsatz pro Quartal.
2. Setze die **vier Quartalssummen** mit `np.stack` und die zugehörigen **Durchschnittswerte** zu einer Tabelle zusammen:
   Zeile 0 = Summen, Zeile 1 = Durchschnitte. Shape prüfen!
3. Hänge eine dritte Zeile mit dem **Anteil in %** jedes Quartals am Jahresumsatz an (`np.concatenate`).

In [34]:
# Dein Code hier

### Übung 9 – Neue Sorte im Lager

📌 **Thema:** Kombinieren und Aufteilen (Block C)

Kiez Kaffee nimmt die Sorte **„Kenia"** ins Sortiment auf. Bestand in den 4 Filialen: `np.array([10, 0, 8, 5])` kg, Preis 15 €/kg.

1. Hänge Kenia als **neue Spalte** an `bestand_kg` an. (Tipp: Die neue Spalte braucht die Form `(4, 1)`.)
2. Erweitere auch `sorten` und `preis_kg` um Kenia.
3. Prüfe: Passen die Shapes von `bestand_kg` (Spalten) und `preis_kg` jetzt zusammen?

In [35]:
# Dein Code hier

## 19 – Thema: Matrizen und Gleichungssysteme

### Übung 10 – Lagerwert

📌 **Thema:** Matrizen und Gleichungssysteme (Block D)

Arbeite mit `bestand_kg` und `preis_kg`.

1. Berechne den **Lagerwert in €** pro Filiale mit **einer** Matrixmultiplikation.
2. Berechne zum Vergleich den Lagerwert **pro Filiale und Sorte** mit `*` (Broadcasting). Was ist der Unterschied zu Aufgabe 1?
3. Prüfe: Ergibt die Zeilensumme aus Aufgabe 2 dasselbe wie Aufgabe 1?

In [36]:
# Dein Code hier

### Übung 11 – Neue Hausmischung

📌 **Thema:** Matrizen und Gleichungssysteme (Block D)

Kiez Kaffee möchte **20 kg** einer neuen Mischung aus **Brasilien (x), Äthiopien (y) und Indien (z)** herstellen.

- Die Mischung soll insgesamt **193 €** im Einkauf kosten (Preise: Brasilien 8 €, Äthiopien 14 €, Indien 7,50 € pro kg).
- Es soll **genauso viel Äthiopien wie Indien** enthalten sein.

1. Stelle die drei Gleichungen auf (auf Papier) und schreibe sie als `A` und `b`.
2. Löse das System mit `np.linalg.solve` und runde auf 2 Stellen.
3. Probe mit `@`.
4. Reicht der **Lagerbestand von Wedding** (`bestand_kg[3]`, Spalten 0, 1, 4) für die Mischung? Welche Sorte fehlt?

In [37]:
# Dein Code hier

## 20 – Thema: Sortieren

### Übung 12 – Ranglisten im Lager

📌 **Thema:** Sortieren (Block E)

1. Berechne den **Lagerwert pro Sorte** über alle Filialen (Tipp: erst Summe pro Spalte, dann mal Preis).
2. Erstelle eine **Rangliste der Sorten** nach Lagerwert (höchster zuerst) und gib Namen und Werte aus.
3. Sortiere die **Filialen** nach ihrem gesamten Lagerbestand in kg (absteigend). Gib die Namen aus.

In [38]:
# Dein Code hier

### Übung 13 – Beste und schlechteste Tage

📌 **Thema:** Sortieren (Block E)

Arbeite mit `tage_jahr`.

1. Gib die **5 höchsten** und die **5 niedrigsten** Tagesumsätze aus.
2. An welchen **Tagesnummern** (1–364) wurden die 5 höchsten Umsätze erzielt?
3. In welcher **Kalenderwoche** lagen diese Tage? (Tipp: Tagesindex `// 7 + 1`)
4. **Bonus:** Wie hoch ist der Durchschnitt, wenn man die 5 höchsten und die 5 niedrigsten Tage **weglässt**?

In [39]:
# Dein Code hier

---
## Rückblick auf die NumPy-Woche

| Notebook | Mathe | NumPy |
|---|---|---|
| 1 | Boolesche Algebra | Arrays erstellen, Indexing, Slicing, Masken mit `&` `\|` `~` |
| 2 | Mengenlehre | `unique`, `isin`, Mengenoperationen, `np.where`, Fancy Indexing |
| 3 | Potenzen, Wurzeln, Log | Vektorisierung, ufuncs, Datentypen und Fallstricke |
| 4 | Prozent, Dreisatz, Wachstum | Aggregationen mit `axis`, `cumsum`/`cumprod`, NaN, `clip`, Broadcasting |
| 5 | Gleichungssysteme, Funktionen | `reshape`, `concatenate`/`stack`/`split`, `@`, `linalg.solve`, `sort`/`argsort` |

**Wie geht es weiter?** Alles, was du diese Woche gelernt hast, steckt in **Pandas**.
Ein Pandas-DataFrame ist im Kern ein NumPy-Array mit **Spaltennamen** und **Zeilenbeschriftungen**. Masken, `axis`, NaN und Broadcasting funktionieren dort genauso.